# Generated by Django 4.0.5 on 2022-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='previous_reservation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
